apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hocs-reporting-service
  labels:
    version: {{.VERSION}}
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hocs-reporting-service
  targetCPUUtilizationPercentage: 80
