---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: nginx-external
    stable.k8s.psg.io/kcm.provider: http
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: hocs-reporting-basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
  name: hocs-reporting-service
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-reporting-service
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: hocs-frontend-external-tls
