---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-reporting-service
  name: hocs-reporting-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: hocs-data-service
